apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: janneleppanen/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*js"
            dest: .
    - image: janneleppanen/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*js"
            dest: .
    - image: janneleppanen/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*js"
            dest: .
    - image: janneleppanen/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*js"
            dest: .
    - image: janneleppanen/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*js"
            dest: .
    - image: janneleppanen/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*js"
            dest: .
